### ISSUE TITLE
Sprout forms not populated in the admin dashboard

### ISSUE THREAD

**Issue by Aayushi1071** [barrelstrength/sprout#102]
### Description (screenshots, logs, ...)
Recently I lost all my sprout forms and entries. The forms are visible in the database but cannot be seen on the admin dashboard, it shows count 0. 
If it is relevant I recently deleted a site from the Craft CMS

### Additional info

- Craft version: Craft Pro 3.4.28
- PHP version: 7.4.18
- Database driver & version:  MySQL 5.7.38
- Plugins & versions: 3.11.2

**Comment by BenParizek** [comment]
@Aayushi1071 Thinking out loud here, Sprout Forms for Craft 3 doesn't support multisite, so all the Sprout Forms content should be associated with the primary site ID. Looking at the craft [deleteSite method](https://github.com/craftcms/cms/blob/515678a45df7d7ab70692dbc282d1452159a3ee1/src/services/Sites.php#L868-L870), Craft doesn't allow you to delete the primary site. Is it possible you created forms or entries on your primary site, switched the primary site to a different one, and then deleted the initial primary site?

Do you see any errors in the logs or in the browser console or browser network tab on the page that isn't loading what you see in the database? Do you have a back up db to review if anything changed about how the Sprout Forms content was/is saved or test recreating the issue?

If it'd be easier to talk through this and look through your db on a screenshare, feel free to [book a meeting](https://barrelstrengthdesign.com/schedule/ben-parizek/) with me or drop me a note at sprout@barrelstrengthdesign.com and propose some times that work for you.

**Comment by Aayushi1071** [comment]
@BenParizek unfortunately, it is the first one. I have changed the primary site and deleted the old primary site. But the data regarding the forms and entries still lies in the database. Now I need help to connect them with the new primary site.

**Comment by BenParizek** [comment]
@Aayushi1071 You'll have to verify this in your database but I believe the issue may be that the `siteId` did not get updated somewhere. There are two places this is possible in the db, in `elements_sites.siteId` and in the relevant Sprout Forms content tables which get created on the fly for each form you create. They would be named something like `sproutformscontent_yourFormHandle.siteId`

To resolve this I think you'll want to check the `sites` table and the `sites.id` that represents your new site. I'll assume your old Primary site was site ID `1` and let's say your new primary site is ID `3` in this example.

Then check your `elements_sites` table and Sprout Forms content tables for a mismatch in the IDs `sproutformscontent_yourFormHandle`

You can query all the Entry Elements directly using this query (and make sure that your tables are named what they are in the query, some sites have the `craft_` prefix before the table names): 

```
SELECT *
FROM elements AS elements
JOIN elements_sites AS elements_sites
    ON elements.id = elements_sites.elementId
WHERE type = 'barrelstrength\\sproutforms\\elements\\Entry';
```

Once you find out where the issue is, you can manually update the site IDs to the correct Site IDs or use a query like the following. The following query modifies data in the database so backup your database first so that you can revert if this doesn't behave the way you expect.

```
UPDATE sproutformscontent_yourFormHandle
SET siteId = 3 ## New Site ID
WHERE siteId = 1; ## Old Site ID
```

That query would fix the issue for Form Entry Elements for one form content table. If you have multiple forms you may have to do this multiple times. This is my current best guess at where the issue lies but it's possible that the steps you took lead to a different scenario than my tests. If the issue doesn't appear to be with the sproutformscontent table IDs, I may need to see your db to make a more informed suggestion as to how to get things restored. If these changes are outside your comfort zone feel free to schedule a call and we can walk through these updates on a screenshare together.
