### ISSUE TITLE
Iphone 11 Keyboard Controles

### ISSUE THREAD

**Issue by cjwhitedev** [barrelstrength/sprout#151]
### Description (screenshots, logs, ...)
The arrows and done button on iphone 11 are not doing anything inside the sprout form.

### Steps to reproduce
1. Click into a form field on an iphone 11
2. Try hitting the arrows or the done button

### Additional info
- Craft version: 3

**Comment by BenParizek** [comment]
@cjwhitedev 

Due to the complexity of the Form Builder UI we haven't attempted to optimize it for mobile use, so there may be a handful of issues to consider there. I'm going to consider this a feature request right now in the more general sense of mobile support. Let me know if you feel we're overlooking a critical use case.
