### ISSUE TITLE
Sitemaps - Craft 4 Support

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/sprout#191]
Sprout Sitemaps is in the process of being updated to Craft 4. Please see the statement in our docs for additional details:
https://sprout.barrelstrengthdesign.com/docs/support/road-map.html

Follow this thread if you'd like to be notified when the upgrade is ready.

**Comment by mikehayesuk** [comment]
Hi,

I'm just wondering whether any progress has been made on this?

I have a client site which needs upgrading to Craft 4 but this plugin is blocking the upgrade at the moment. We have to decide whether to replace this plugin or hold on a bit longer depending on whether the update is due to be ready soon (i.e. in the coming weeks).

Thanks!
Mike

**Comment by dseegers** [comment]
Hey,

Just wanted to check if there's been any progress on this. We need to decide whether to replace this plugin or hold on a bit longer.

Thanks!

Daan

**Comment by BenParizek** [comment]
Getting close. While I'm still refraining from making any promises, there is a good chance it may be ready for release within the next couple of weeks.

**Comment by mikolamin** [comment]
@BenParizek  Do you have update?

**Comment by BenParizek** [comment]
Hey folks. I've just cut a release adding Craft 4 support.

https://plugins.craftcms.com/sprout-sitemaps?craft4

Update Notes:
https://sprout.barrelstrengthdesign.com/docs/craft-v4/update-guides/sitemaps.html#v4-44-444-september-25-2023

There is a new Content Query Sitemap feature if you need to manage any Sitemaps with refined queries:

![image](https://github.com/barrelstrength/sprout/assets/309735/5d975add-e284-4e71-b653-604d12299850)
