### ISSUE TITLE
Craft 4, Sprout Seo 4.44.444: Meta Details fields

### ISSUE THREAD

**Issue by WHITE-developer** [barrelstrength/sprout#323]
### Description

In the update guide, it is described that Metadata Field settings are removed. https://sprout.barrelstrengthdesign.com/docs/craft-v4/update-guides/seo.html#editable-field-metadata-field-setting-has-been-removed
But I see them in the metaData field:
![image](https://github.com/barrelstrength/sprout/assets/22771556/1c79e6ca-45ef-4312-8d5f-587cb97c6cba)
When I enable them I get the following error message
![image](https://github.com/barrelstrength/sprout/assets/22771556/fca0bb79-78b2-4524-b6a9-beff15da8a9a)
So how can I edit the Metadata fields? because now I can only edit the title and description:
Craft 4: ![image](https://github.com/barrelstrength/sprout/assets/22771556/d783ca72-85ad-4422-98b1-22081af27e2a)
We want to edit all the settings like in Craft 3:
Craft 3:![image](https://github.com/barrelstrength/sprout/assets/22771556/6cc4caba-cd01-4c6e-beab-5c75d6fc2eaf)

### How to reproduce

Update to craft 4 and sprout-seo to 4.44.444-beta.1 and enable the Meta details field
![image](https://github.com/barrelstrength/sprout/assets/22771556/469455a3-b957-4822-93a9-1c42c7ce49fa)

### Sprout Version

4.44.444-beta.1

### Craft Version

4.9.3

### Database Type Version

MySQL

**Comment by BenParizek** [comment]
@WHITE-developer The "Editable Field" was a specific setting within the Metadata field that we removed. It doesn't appear like you are using it so you probably don't need to worry about it.

It appears the issue here is just a filepath casing issue. Your system seems to be case sensitive and has revealed a mistake in my code. I've just released v4.44.444-beta.4 which should solve this
